### PR TITLE
Add support for both ancient and lineage

### PR DESCRIPTION
**Pull request by ghost**
This change makes it possible to use the `eleven` branch on both Ancient and LineageOS manifests.

`TARGET_2ND_ARCH_VARIANT` was changed back to `armv8-a` because Nokia 8 doesn't have a `armv8-2a` CPU.

### CODE REVIEW

**Comment by ghost** [comment]
I've made a change to fix an error when compiling SELinux profiles for LineageOS https://github.com/GPUCode/device_nokia_NB1/pull/1/commits/5aedeb68e91ed48dd388670ac00a69f64118f703. 

I think it doesn't occur on AncientOS because they allow neverallows, though I couldn't know because their manifests aren't public.

**Comment by raphaelthegreat** [comment]
The selinux change is more than welcome, but I changed the TARGET_2ND_ARCH_VARIANT because AncientOS refuses to build, if it isn't set as armv8-2a. Aside from that though, I don't think that having support for both LineageOS and AncientOS in the same tree at the same time, is such a good idea. My dot11 branch is actually meant for LineageOS even though I intended to build DotOS with it. AncientOS requires some minor modifications to the tree that I don't think would ever be accepted by LineageOS if it were to ever get official support. 

My workflow involves having many branches on this central repo and forking a specific branch on the target ROM (this case ancient-devices has forked my eleven branch). I just haven't merged the sepolicy yet on the LineageOS (dot11) branch cause I was busy with Ancient. So keeping the eleven branch as Ancient exclusive would allow us to push more unofficial custom patches that LineageOS probably wouldn't allow.

**Comment by raphaelthegreat** [comment]
> I've made a change to fix an error when compiling SELinux profiles for LineageOS [5aedeb6](https://github.com/GPUCode/device_nokia_NB1/commit/5aedeb68e91ed48dd388670ac00a69f64118f703).
> 
> I think it doesn't occur on AncientOS because they allow neverallows, though I couldn't know because their manifests aren't public.

I will try to enable neverallows if they have them disabled as it's good to have them enabled to keep the sepolicy secure.

**Comment by ghost** [comment]
@GPUCode Will you copy over your changes from eleven to dot11? I really don't want to use AncientOS, I tried it out from https://sourceforge.net/projects/ancientrom/files/NB1/ and it wasn't the best. I also would like to build the ROM myself and that is not possible because AncientOS' manifests aren't public.

**Comment by raphaelthegreat** [comment]
> @GPUCode Will you copy over your changes from eleven to dot11? I really don't want to use AncientOS, I tried it out from https://sourceforge.net/projects/ancientrom/files/NB1/ and it wasn't the best. I also would like to build the ROM myself and that is not possible because AncientOS' manifests aren't public.

AncientOS isn't my cup of tea either, but many users requested it. I don't like ROMs that have too many features and implement so many hacks and patches and that fact that it's closed source makes it even worse. However I don't really maintain AncientOS, I only update the trees and provide fixes when needed. I prefer crdroid or even vanilla LineageOS and I might maintain it in the future, but currently my device is broken and I rely exclusively on testers to test and validate ROMs.

You can already build LineageOS if you want from dot11 but it will be permissive instead of enforcing. I just need to cherry pick the sepolicy commits there (and your neverallow fix) and it should work.

**Comment by ghost** [comment]
Thanks for the info. Somewhat related but would you like me to make a separate pull request with only the SELinux neverallow fix?

**Comment by ghost** [comment]
I guess mixing both LineageOS and AncientOS is unacceptable for you.

**Comment by raphaelthegreat** [comment]
> I guess mixing both LineageOS and AncientOS is unacceptable for you.

"Unacceptable" is a harsh word. I merely want the tree to remain clean and all the ROMs (AncientOS, crDroid, LineageOS) to reside in different branches, because each one might have different patches needed to build and different overlays to set to enable specific features. LineageOS is very strict on what it allows on the tree and what is does not, which is why I don't want to mix other ROMs with it.

**Comment by raphaelthegreat** [comment]
> Thanks for the info. Somewhat related but would you like me to make a separate pull request with only the SELinux neverallow fix?

No need to open an entire pull request for a single commit, I can cherry pick it from your device tree.

**Pull request closed without merging**
